'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateMachine

    '''<summary>
    '''btnBackToGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackToGrid As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''formLayoutMachine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLayoutMachine As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtMachineName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMachineName As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtMachineTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMachineTag As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmbFactory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFactory As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtLocationInFactory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocationInFactory As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''dateInstall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateInstall As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''btnCreateMachine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateMachine As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblStatusMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusMessage As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''SqlDataSourceFactories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceFactories As Global.System.Web.UI.WebControls.SqlDataSource
End Class
