'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Inventory

    '''<summary>
    '''gridInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridInventory As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''SqlDataSourceInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceInventory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceFactories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceFactories As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceParts As Global.System.Web.UI.WebControls.SqlDataSource
End Class
