'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SchedulePlanner

    '''<summary>
    '''ASPxScheduler1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxScheduler1 As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler

    '''<summary>
    '''SqlDataSourcePlans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePlans As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceMachines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceMachines As Global.System.Web.UI.WebControls.SqlDataSource
End Class
