'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewTicket

    '''<summary>
    '''hfTicketID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTicketID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblTicketID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''formLayoutDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLayoutDetails As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''lblMachine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMachine As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblFactory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFactory As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblCreatedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedOn As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedBy As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''memoProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoProblem As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''lblAssignedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignedTo As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''pageControlActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageControlActions As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''formLayoutActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLayoutActions As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmbStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStatus As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''btnUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateStatus As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''pnlAssignmentControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssignmentControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmbTechnician control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTechnician As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''btnAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssign As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmbExternalEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbExternalEngineer As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''btnAssignExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssignExternal As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''formLayoutParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLayoutParts As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmbParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbParts As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''spinQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spinQuantity As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''btnAddPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPart As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''formLayoutProcurement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLayoutProcurement As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtPartNameNeeded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNameNeeded As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtPartNumberNeeded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNumberNeeded As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''spinQuantityNeeded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spinQuantityNeeded As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''cmbSuggestedSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSuggestedSupplier As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''memoRequestNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoRequestNotes As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''btnSubmitRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitRequest As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnFindSimilar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindSimilar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblActionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActionStatus As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''pnlAttachChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAttachChecklist As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''formLayoutChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLayoutChecklist As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmbChecklists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbChecklists As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''btnAttachChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAttachChecklist As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''pnlActiveChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActiveChecklist As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblChecklistName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChecklistName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridChecklistTasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridChecklistTasks As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''gridLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridLogs As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''memoNewLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoNewLog As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''btnAddLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddLog As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''gridPartsUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPartsUsed As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''popupSimilarIssues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupSimilarIssues As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''gridSimilarIssues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridSimilarIssues As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''SqlDataSourceTechnicians control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTechnicians As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceInventoryParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceInventoryParts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceExternalEngineers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceExternalEngineers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceMasterChecklists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceMasterChecklists As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSuppliers As Global.System.Web.UI.WebControls.SqlDataSource
End Class
